# This workflow builds on push to main using nuitka for Windows and Linux

name: Build Cross-Platform

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r build_requirements.txt
          pip install nuitka

      - name: Build TBMM for Windows
        run: |
          nuitka --onefile --follow-imports --windows-console-mode=disable --windows-icon-from-ico="Images\TBMM icon.ico" --include-data-dir="Images=Images" --enable-plugin=tk-inter --assume-yes-for-downloads "The Bibites Mod Manager.py"

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: TBMM-Windows
          path: The Bibites Mod Manager.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y python3-tk
          python -m pip install --upgrade pip
          pip install -r build_requirements.txt
          pip install nuitka

      - name: Build TBMM for Linux
        run: |
          nuitka --onefile --follow-imports --include-data-dir="Images=Images" --enable-plugin=tk-inter --assume-yes-for-downloads "The Bibites Mod Manager.py"

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: TBMM-Linux
          path: The\ Bibites\ Mod\ Manager.bin