# This workflow builds on push to main using nuitka for Windows and Linux

name: Build Cross-Platform

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  generate-nightly-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set nightly version
        id: set-version
        run: |
          VERSION=nightly-$(date +'%Y%m%d')
          echo "$VERSION" > version.txt
          sed -i "s/__VERSION__/$VERSION/" "The Bibites Mod Manager.py"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Commit and push nightly version
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git add version.txt "The Bibites Mod Manager.py"
          git commit -m "Nightly build: update version to ${{ steps.set-version.outputs.version }}" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}

  build-windows:
    needs: generate-nightly-version
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: pip-${{ runner.os }}-${{ hashFiles('**/build_requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-
      
      - name: Cache Nuitka
        uses: actions/cache@v4
        with:
          path: .nuitka-cache
          key: nuitka-${{ runner.os }}-${{ hashFiles('**/*.py') }}
          restore-keys: |
            nuitka-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r build_requirements.txt
          pip install nuitka

      - name: Build TBMM for Windows
        run: |
          nuitka --onefile --follow-imports --windows-console-mode=disable --windows-icon-from-ico="Images\TBMM icon.ico" --include-data-dir="Images=Images" --enable-plugin=tk-inter --assume-yes-for-downloads "The Bibites Mod Manager.py"

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: TBMM-Windows
          path: The Bibites Mod Manager.exe

  build-linux:
    needs: generate-nightly-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/build_requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-
      
      - name: Cache Nuitka
        uses: actions/cache@v4
        with:
          path: .nuitka-cache
          key: nuitka-${{ runner.os }}-${{ hashFiles('**/*.py') }}
          restore-keys: |
            nuitka-${{ runner.os }}-

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y python3-tk ccache
          python -m pip install --upgrade pip
          pip install -r build_requirements.txt
          pip install nuitka

      - name: Build TBMM for Linux
        run: |
          nuitka --onefile --follow-imports --include-data-dir="Images=Images" --enable-plugin=tk-inter --assume-yes-for-downloads "The Bibites Mod Manager.py"

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: TBMM-Linux
          path: The\ Bibites\ Mod\ Manager.bin