# This workflow builds on push to main using nuitka for Windows and Linux

name: Build Cross-Platform

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Write nightly version to file and update script
        shell: powershell
        run: |
          $version = "nightly-$(Get-Date -Format 'yyyyMMdd')"
          Set-Content -Path "version.txt" -Value $version
          (Get-Content "The Bibites Mod Manager.py") -replace '__VERSION__', $version | Set-Content "The Bibites Mod Manager.py"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: pip-${{ runner.os }}-${{ hashFiles('**/build_requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-
      
      - name: Cache Nuitka
        uses: actions/cache@v4
        with:
          path: .nuitka-cache
          key: nuitka-${{ runner.os }}-${{ hashFiles('**/*.py') }}
          restore-keys: |
            nuitka-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r build_requirements.txt
          pip install nuitka

      - name: Build TBMM for Windows
        run: |
          nuitka --onefile --follow-imports --windows-console-mode=disable --windows-icon-from-ico="Images\TBMM icon.ico" --include-data-dir="Images=Images" --enable-plugin=tk-inter --assume-yes-for-downloads "The Bibites Mod Manager.py"

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: TBMM-Windows
          path: The Bibites Mod Manager.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Write nightly version to file
        run: |
          version="nightly-$(date +'%Y%m%d')"
          echo "$version" > version.txt
          sed -i "s/__VERSION__/$version/" "The Bibites Mod Manager.py"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/build_requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-
      
      - name: Cache Nuitka
        uses: actions/cache@v4
        with:
          path: .nuitka-cache
          key: nuitka-${{ runner.os }}-${{ hashFiles('**/*.py') }}
          restore-keys: |
            nuitka-${{ runner.os }}-

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y python3-tk ccache
          python -m pip install --upgrade pip
          pip install -r build_requirements.txt
          pip install nuitka

      - name: Build TBMM for Linux
        run: |
          nuitka --onefile --follow-imports --include-data-dir="Images=Images" --enable-plugin=tk-inter --assume-yes-for-downloads "The Bibites Mod Manager.py"

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: TBMM-Linux
          path: The\ Bibites\ Mod\ Manager.bin